Implement Warehouse API
kalkolay/demo-service-121 pull request #3
Opened 2022-11-28 14:22 UTC by kalkolay

- API can be found in `com/itmo/microservices/demo/warehouse`
- No business logic
- Made `data class Product` params non-null

2022-11-30 10:39 UTC, afterbvrner requested changes

2022-11-30 10:39 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/warehouse/api/controller/WarehouseController.kt
> +    fun allItems(): Nothing = TODO("Not yet implemented")
Не соответствует system_api - путь должен быть /items, возвращаемый тип - List<CatalogItemDto>

2022-11-30 10:39 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/warehouse/api/model/WarehouseItemModel.kt
> +    val id: UUID?,
Не хватает полей:
CatalogItemDto {
	id: UUID,
	title: String,
	description: String,
	price: Int = 100,
	amount: Int
}

2022-11-30 16:34 UTC, kalkolay commented
Замечания исправлены @afterbvrner

2022-12-04 16:09 UTC, afterbvrner requested changes

2022-12-04 16:09 UTC, afterbvrner commented on src/main/kotlin/com/itmo/microservices/demo/warehouse/api/controller/WarehouseController.kt
> +    @GetMapping("/items")
/items?available={available}&size={size}

2022-12-04 16:43 UTC, merged